Rails.application.routes.draw do
  resources :destinations
  resources :streets
  resources :countries
  get 'home/index'
  resources :users
  root to: 'home#index'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)


  post "/users/:user_id/edit", to: 'users#edit'

  # post '/courses/:course_id', to: 'courses#show'
  # post "/add_course/:user_id/:course_id", to: 'registrations#add_course'
  # delete "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'
  #
  # get "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'

end
